steps:
  - id: 'branch name'
    name: 'alpine'
    entrypoint: 'sh'  
    args: 
    - '-c'
    - | 
        echo "***********************"
        echo "$BRANCH_NAME"
        echo "***********************"
  - name: python:3.10
    entrypoint: python
    args: ['-m', 'pip', 'install', '--upgrade', 'pip']
  - name: python:3.10
    entrypoint: pip
    args: ['install', '-r', 'requirements.txt', '--user']
  - name: python:3.10
    entrypoint: python
    args: ['-m', 'main', '--commit=${SHORT_SHA}']
    dir: 'src/'